{
 "title": "Beer Garden Plugin Performance",
 "description": "A dashboard for plugins in Beer Garden",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": "label_values(bg_plugin_command_latency_seconds_count, system)"
   },
   {
    "name": "system_version",
    "label": "System Version",
    "query": "query_result(bg_plugin_command_latency_seconds_count{system=\"$system\"})"
   },
   {
    "name": "instance_name",
    "label": "Instance Name",
    "query": "query_result(bg_plugin_command_latency_seconds_count{system=\"$system\"})"
   },
   {
    "name": "command",
    "label": "Command",
    "query": "query_result(bg_plugin_command_latency_seconds_count{system=\"$system\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests In Progress",
   "type": "singlestat",
   "description": "Number of requests in progress for the given system",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_in_progress_requests{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\"})"
    }
   ]
  },
  {
   "title": "Current Command Latency",
   "type": "singlestat",
   "description": "How long is it taking to complete command(s) currently averaged over a 5 minute window",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_plugin_command_latency_seconds_sum{system=\"$system\", system_version=~\"$system_version\", instance_name=~\"$instance_name\", command=~\"$command\"}[5m])) /\nsum(rate(bg_plugin_command_latency_seconds_count{system=\"$system\", system_version=~\"$system_version\", instance_name=~\"$instance_name\", command=~\"$command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Command Completion Graph",
   "type": "graph",
   "description": "Completed commands vs waiting commands",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bg_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", command=\"$command\"})",
     "legendFormat": "$command created"
    },
    {
     "expr": "sum(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", command=\"$command\"})",
     "legendFormat": "[[command]] completed"
    }
   ]
  },
  {
   "title": "Completed Requests per Second",
   "type": "singlestat",
   "description": "Number of requests processed per second over the last 5 minutes",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", command=\"$command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total  Successful Commands",
   "type": "singlestat",
   "description": "Number of successes divided by number of requests",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", status=\"SUCCESS\"}) / \nsum(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\"})"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "singlestat",
   "description": "Number of Successful Requests",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", status=\"SUCCESS\"})"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "description": "Number of Failed Requests",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", status=\"ERROR\"})"
    }
   ]
  },
  {
   "title": "Waiting requests",
   "type": "singlestat",
   "description": "Number of requests waiting to be processed by the system.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_queued_requests{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\"})"
    }
   ]
  },
  {
   "title": "Average Total Command Latency",
   "type": "singlestat",
   "description": "On average, across the lifetime of this plugin, what is the latency of the command(s)",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(bg_plugin_command_latency_seconds_sum{system=\"$system\", system_version=~\"$system_version\", instance_name=~\"$instance_name\", command=~\"$command\"}) /\nsum(bg_plugin_command_latency_seconds_count{system=\"$system\", system_version=~\"$system_version\", instance_name=~\"$instance_name\", command=~\"$command\"})"
    }
   ]
  },
  {
   "title": "Requests Created Per Second",
   "type": "singlestat",
   "description": "Number of requests created processed per second over the last 5 minutes",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", command=~\"$command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total  Failed Commands",
   "type": "singlestat",
   "description": "Number of errors divided by number of completed",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\", status=\"ERROR\"}) / \nsum(bg_completed_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\"})"
    }
   ]
  },
  {
   "title": "Total Number of Requests",
   "type": "singlestat",
   "description": "The total number of requests for this system.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_requests_total{system=\"$system\", instance_name=~\"$instance_name\", system_version=~\"$system_version\"})"
    }
   ]
  },
  {
   "title": "Command Latency",
   "type": "graph",
   "description": "Average command latency by command for this system over the last 5 minutes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(bg_plugin_command_latency_seconds_sum{system=\"$system\", system_version=~\"$system_version\", instance_name=~\"$instance_name\", command=~\"$command\"}[5m]) / \nrate(bg_plugin_command_latency_seconds_count{system=\"$system\", system_version=~\"$system_version\", instance_name=~\"$instance_name\", command=~\"$command\"}[5m])"
    }
   ]
  }
 ]
}