export const FETCH_CONFIG_BEGIN = 'FETCH_CONFIG_BEGIN';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';

export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const FETCH_SYSTEMS_BEGIN = 'FETCH_SYSTEMS_BEGIN';
export const FETCH_SYSTEMS_SUCCESS = 'FETCH_SYSTEMS_SUCCESS';
export const FETCH_SYSTEMS_FAILURE = 'FETCH_SYSTEMS_FAILURE';
