import brew_view.handlers.v1.admin
import brew_view.handlers.v1.command
import brew_view.handlers.v1.event
import brew_view.handlers.v1.instance
import brew_view.handlers.v1.job
import brew_view.handlers.v1.logging
import brew_view.handlers.v1.permissions
import brew_view.handlers.v1.queue
import brew_view.handlers.v1.request
import brew_view.handlers.v1.role
import brew_view.handlers.v1.system
import brew_view.handlers.v1.token
import brew_view.handlers.v1.user
