{
 "title": "Beer Garden Performance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Current Operating Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "In progress commands",
   "type": "singlestat",
   "description": "How many requests have a status of IN_PROGRESS",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(bg_in_progress_requests)" }
   ]
  },
  {
   "title": "Queued Commands",
   "type": "singlestat",
   "description": "How many requests are waiting to be IN_PROGRESS",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(bg_queued_requests)" }
   ]
  },
  {
   "title": "Successful Commands",
   "type": "singlestat",
   "description": "Total Number of successfully completed commands divided by the total number of commands created",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_completed_requests_total{status=\"SUCCESS\"}) / \nsum(bg_requests_total)"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "singlestat",
   "description": "Percentage of commands that failed",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_completed_requests_total{status=\"ERROR\"}) / \nsum(bg_requests_total)"
    }
   ]
  },
  {
   "title": "Total Request Completion",
   "type": "singlestat",
   "description": "Total number of requests completed divided by the number of requests created.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bg_completed_requests_total) / sum(bg_requests_total)"
    }
   ]
  },
  {
   "title": "Rate of server errors",
   "type": "singlestat",
   "description": "Current Percentage of API calls that ended in 5XX averaged over a 5 minute time window.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_http_api_latency_seconds_count{status=~\"5..\"}[5m])) / sum(rate(bg_http_api_latency_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Rate of Client Errors",
   "type": "singlestat",
   "description": "Current Percentage of API calls that ended in 4XX averaged over a 5 minute time window.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_http_api_latency_seconds_count{status=~\"4..\"}[5m])) / sum(rate(bg_http_api_latency_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Requests Created Recently",
   "type": "singlestat",
   "description": "The total number of requests that have been created in the last X minutes",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "bg_http_api_latency_seconds_count{route=\"/api/v1/requests\", method=\"POST\", status=~\"2..\"}"
    }
   ]
  },
  {
   "title": "Successful Commands per Second",
   "type": "singlestat",
   "description": "Current rate of successful request completion per second, averaged over a 5 minute window",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_completed_requests_total{status=\"SUCCESS\"}[5m]))"
    }
   ]
  },
  {
   "title": "Failed Commands per Second",
   "type": "singlestat",
   "description": "Current rate of error request completion per second, averaged over a 5 minute window",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_completed_requests_total{status=\"ERROR\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests Created per Second",
   "type": "singlestat",
   "description": "Current rate of request creation per second, averaged over a 5 minute window",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Current API Calls per second",
   "type": "singlestat",
   "description": "The average number of API calls per second averaged across all routes in 5 minute windows",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(bg_http_api_latency_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Command Completion Graph",
   "type": "graph",
   "description": "Completed commands vs waiting commands",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(bg_requests_total)", "legendFormat": "created" },
    {
     "expr": "sum(bg_completed_requests_total)",
     "legendFormat": "completed"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GUI API Latency",
   "type": "graph",
   "description": "These are the most used routes for our GUI, so we specifically check how long they are taking. This is an average rate over the last 2 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(bg_http_api_latency_seconds_sum{route=\"/api/v1/requests\", method=\"GET\"}[2m]) / rate(bg_http_api_latency_seconds_count{route=\"/api/v1/requests\", method=\"GET\"}[2m])"
    },
    {
     "expr": "rate(bg_http_api_latency_seconds_sum{route=\"/api/v1/systems\", method=\"GET\"}[2m]) / rate(bg_http_api_latency_seconds_count{route=\"/api/v1/systems\", method=\"GET\"}[2m])"
    }
   ]
  },
  {
   "title": "Request API Latency",
   "type": "graph",
   "description": "These are the most used routes for plugins to use. We monitor their status again averaged over a 2 minute window",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(bg_http_api_latency_seconds_sum{route=~\"/api/v1/requests\"}[2m]) / rate(bg_http_api_latency_seconds_count{route=~\"/api/v1/requests\"}[2m])"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "description": "How much memory is being used.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Average API Latency over 5 minutes",
   "type": "graph",
   "description": "Broken down by endpoint/status code how long is the API server taking to respond",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(bg_http_api_latency_seconds_sum[5m]) / rate(bg_http_api_latency_seconds_count[5m])"
    }
   ]
  }
 ]
}