name: Develop Push

on:
  push:
    branches:
      - develop

jobs:
  docker-publish-src-unstable:
    name: Docker Publish Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12","3.13", "3.14"]
        os: ["ubuntu-latest"]
        include:
          - python-version: "3.7"
            os: "ubuntu-22.04"

    defaults:
      run:
        working-directory: ./src/app

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Dependencies 
        run: make deps 

      - name: Build and Publish Unstable Images
        run: make publish-docker-unstable PYTHON_VERSION=${{ matrix.python-version }}

  docker-publish-src-unstable-latest:
    name: Docker Publish Python ${{ matrix.python-version }} Latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    defaults:
      run:
        working-directory: ./src/app

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Dependencies 
        run: make deps    

      - name: Build and Publish Unstable Images
        run: make publish-docker-unstable-latest PYTHON_VERSION=${{ matrix.python-version }}

  docker-publish-ui-unstable:
    name: Docker Publish UI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/ui

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        run: make deps publish-docker-unstable
        
  CodeCoverage:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./src/app

    strategy:
      matrix:
        python-version: ["3.11"]
        os: ["ubuntu-latest"]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    name: Code Coverage OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Need to update if we support other OS's
      - name: Cache PIP Install
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-coverage-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-coverage

      - name: Make Deps
        run: |
          make deps
          pip install pytest
          pip install pytest-cov

      - name: Generate coverage report
        continue-on-error: true
        run: |
          coverage run --source beer_garden -m pytest test --tb=no --ignore $(TEST_DIR)/api/http/unit/handlers/v1/event_test.py
          coverage report -m
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
