name: Release Docker bgio/build Images

on: workflow_dispatch

jobs:

  docker-publish-python:
    name: Docker Publish bgio/build:python${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.11.14","3.12.12","3.13.9", "3.14.0"]
        python-version: ["3.14.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        working-directory: ./docker/dockerfiles/build
        run: make build-image-centos7 PYTHON_VERSION=${{ matrix.python-version }}

  docker-publish-rocky9-python:
    name: Docker Publish bgio/build:rocky9-python${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # python-version: ["3.11.14","3.12.12","3.13.9", "3.14.0"]
        python-version: ["3.14.0"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        working-directory: ./docker/dockerfiles/build
        run: make build-image-rocky9 PYTHON_VERSION=${{ matrix.python-version }}
