name: Pull Request -- React

on: 
  pull_request:
    paths:
      - 'src/react/**'
      - '.github/workflows/pull_request_react.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  UILinting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node: ["20"]

    name: UI Linting OS ${{ matrix.os }} - Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install
        working-directory: ./src/react

      - name: Run Tests
        run: make lint
        working-directory: ./src/react

  Vitest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]

    name: Vitest OS ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: make test_docker_image
        working-directory: ./src/react
      
      - name: Run Tests
        run: make test
        working-directory: ./src/react

  Playwright:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node: ["20"]
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm ci
      working-directory: ./src/react
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./src/react
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./src/react
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./src/react/playwright-report/
        retention-days: 7
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        working-directory: ./src/react

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        working-directory: ./src/react
        with:
          urls: |
            http://localhost:3002/
            http://localhost:3002/about
          uploadTargets: temporary-public-storage
