name: Release

on:
  push:
    tags:
      - '*'

jobs:
  github-release:
    name: Github Release
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false


  pypi-publish:
    name: PyPI Publish
    runs-on: ubuntu-22.04
    needs: github-release
    environment:
      name: release
      url: https://pypi.org/p/beer-garden
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Un-comment if you need to do a partial release
    # if: false

    defaults:
      run:
        working-directory: ./src/app

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Cache PIP Install
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-3.11-pip-build-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-3.11-pip-build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Make Package
        run: make package

      - name: Check Package Distributions
        run: python -m twine check dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: src/app/dist
          verify-metadata: false

  pypi-verify:
    name: Verify PyPI Publish
    runs-on: ubuntu-22.04
    needs: pypi-publish
    if: always()

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Check PyPi
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 120
          max_attempts: 5
          retry_on: error
          retry_wait_seconds: 10
          command: pip install beer-garden==${GITHUB_REF#refs/tags/}


  docker-publish-ui:
    name: Docker Publish UI
    runs-on: ubuntu-latest
    needs: pypi-verify
    if: ${{always() && needs.pypi-verify.result == 'success'}}

    defaults:
      run:
        working-directory: ./src/ui

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        run: make deps publish-docker VERSION=${GITHUB_REF#refs/tags/}

  docker-publish-ui-react:
    name: Docker Publish UI
    runs-on: ubuntu-latest
    needs: pypi-verify
    if: ${{always() && needs.pypi-verify.result == 'success'}}

    defaults:
      run:
        working-directory: ./src/react

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        run: make deps publish-docker VERSION=${GITHUB_REF#refs/tags/}

  docker-publish-src:
    name: Docker Publish Src - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    needs: pypi-verify
    if: ${{always() && needs.pypi-verify.result == 'success'}}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12","3.13", "3.14"]
        os: ["ubuntu-latest"]
        include:
          - python-version: "3.11"
            os: "ubuntu-22.04"


    defaults:
      run:
        working-directory: ./src/app

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        run: make publish-docker VERSION=${GITHUB_REF#refs/tags/} PYTHON_VERSION=${{ matrix.python-version }}

  docker-publish-src-latest:
    name: Docker Publish Src (Latest) - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: pypi-verify
    if: ${{always() && needs.pypi-verify.result == 'success'}}

    strategy:
      matrix:
        python-version: ["3.11"]


    defaults:
      run:
        working-directory: ./src/app

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        run: make publish-docker-latest VERSION=${GITHUB_REF#refs/tags/} PYTHON_VERSION=${{ matrix.python-version }}

  docker-publish-rpm:
    name: Docker Publish - Python ${{ matrix.python-version }} - ${{ matrix.dist }} 
    runs-on: ${{ matrix.os }}
    needs: [docker-publish-src, docker-publish-src-latest]
    # if: ${{always() && needs.docker-publish-src.result == 'success' && needs.docker-publish-src-latest.result == 'success'}}
    if: false

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11","3.12","3.13", "3.14"]
        os: ["ubuntu-latest"]
        dist: ["centos7", "rocky9"]
        include:
          - python-version: "3.11"
            os: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish RPM Images
        run: make publish-docker-rpm VERSION=${GITHUB_REF#refs/tags/} PYTHON_VERSION=${{ matrix.python-version }} DIST=${{ matrix.dist }}


  centos7-rpm-publish:
    name: RPM Publish - ${{ matrix.dist }} - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: [pypi-verify, github-release]
    # if: ${{always() && needs.pypi-verify.result == 'success' && needs.github-release.result == 'success'}}
    if: false

    strategy:
      matrix:
        python-version: ["3.11","3.12","3.13", "3.14"]
        dist: ["centos7"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build RPM
        run: make rpm-build VERSION=${{ steps.get_version.outputs.version }} PYTHON_VERSION=${{ matrix.python-version }} DIST=${{ matrix.dist }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ needs.github-release.outputs.upload_url }}
          asset_path: ./rpm/dist/beer-garden-${{ steps.get_version.outputs.version }}-py${{ matrix.python-version }}.el7.x86_64.rpm
          asset_name: beer-garden-${{ steps.get_version.outputs.version }}-py${{ matrix.python-version }}.el7.x86_64.rpm
          asset_content_type: application/octet-stream

  rocky9-rpm-publish:
    name: RPM Publish - ${{ matrix.dist }} - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: [pypi-verify, github-release]
    if: ${{always() && needs.pypi-verify.result == 'success' && needs.github-release.result == 'success'}}

    strategy:
      matrix:
        python-version: ["3.11","3.12","3.13", "3.14"]
        dist: ["rocky9"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build RPM
        run: make rpm-build VERSION=${{ steps.get_version.outputs.version }} PYTHON_VERSION=${{ matrix.python-version }} DIST=${{ matrix.dist }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ needs.github-release.outputs.upload_url }}
          asset_path: ./rpm/dist/beer-garden-${{ steps.get_version.outputs.version }}-py${{ matrix.python-version }}.el9.x86_64.rpm
          asset_name: beer-garden-${{ steps.get_version.outputs.version }}-py${{ matrix.python-version }}.el9.x86_64.rpm
          asset_content_type: application/octet-stream
